
spring:
  datasource:
    name: aj_book
    url: jdbc:mysql://localhost:3306/ofs?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.fiberhome.owtb.ofsc_crawler.bean,com.fiberhome.owtb.ofsc_crawler.entity

